version: '3'

services:
  tester:
    depends_on:
      webex:
        condition: service_healthy
      langchain:
        condition: service_healthy
      pca:
        condition: service_healthy
    command:
      - pytest