version: '3.8'

volumes:
  NSO-vol:

services:
  webex:
    build:
      context: webex
    container_name: webex
    profiles:
      - prod
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: "webex"
        target: "/app"
    environment:
      - webex_token
      - bot_email
    healthcheck:
      test: "curl localhost:8000 || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    profiles:
      - prod
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "webex:8000"
    environment:
      - NGROK_AUTHTOKEN
    ports:
      - 4040:4040
  langchain:
    build:
      context: langchain
    container_name: langchain
    profiles:
      - prod
    ports:
      - 8001:8000
    volumes:
      - type: bind
        source: "langchain"
        target: "/app"
      - type: bind
        source: "knowledge"
        target: "/app/knowledge"
    environment:
      - OPENAI_API_KEY
      - LD_LIBRARY_PATH=/app/.libs/
    healthcheck:
      test: "curl localhost:8000 || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  pca:
    build:
      context: PCA
    container_name: pca
    profiles:
      - prod
    ports:
      - 8002:8000
    volumes:
      - type: bind
        source: "PCA"
        target: "/app"
    environment:
      - analytics_url
      - accedian_user
      - accedian_password
    healthcheck:
      test: "curl localhost:8000 || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s      
  nso-prod:
    image: cisco-nso-prod:6.1.11.2
    container_name: nso-prod
    profiles:
      - prod
    environment:
      - EXTRA_ARGS=--with-package-reload
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - "2024:2024"
      - "8888:8888"
    volumes:
      - type: bind
        source: NSO/packages
        target: /nso/run/packages
      - type: bind
        source: NSO/log
        target: /log
      - type: volume
        source: NSO-vol
        target: /nso
    healthcheck:
      test: ncs_cmd -c "wait-start 2"
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
  nso-dev:
    image: cisco-nso-dev:6.1.11.2
    container_name: nso-dev
    network_mode: none
    profiles:
      - dev
    volumes:
      - type: bind
        source: NSO/packages
        target: /nso/run/packages
  cml:
    build:
      context: CML
    container_name: cml
    profiles:
      - prod
    ports:
      - 8003:8000
    volumes:
      - type: bind
        source: "CML"
        target: "/app"
    environment:
      - TF_VAR_cml_address
      - TF_VAR_cml_password
      - TF_VAR_cml_user
    healthcheck:
      test: "curl localhost:8000 || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s        
  tester:
    build:
      context: Tester
    container_name: tester
    profiles:
      - prod
    volumes:
      - type: bind
        source: "Tester"
        target: "/app"
    environment:
      - webex_token
      - NGROK_DOMAIN
    depends_on:
      webex:
        condition: service_healthy
      langchain:
        condition: service_healthy
      pca:
        condition: service_healthy
      cml:
        condition: service_healthy
