version: '1.0'

volumes:
  NSO-vol:


networks:
  NSO-net:


services:
  nso-prod:
    image: cisco-nso-prod:6.1.11.2
    container_name: nso-prod
    profiles:
      - prod
    environment:
      - EXTRA_ARGS=--with-package-reload
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    networks:
      - NSO-net
    ports:
      - "2024:2024"
      - "8888:8888"
    volumes:
      - type: bind
        source: ./packages
        target: /nso/run/packages
      - type: bind
        source: ./log
        target: /log
      - type: volume
        source: NSO-vol
        target: /nso
    healthcheck:
      test: ncs_cmd -c "wait-start 2"
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s

  nso-dev:
    image: cisco-nso-dev:6.1.11.2
    container_name: nso-dev
    network_mode: none
    profiles:
      - dev
    volumes:
      - type: bind
        source: ./packages
        target: /nso/run/packages
