[tool.poetry]
name = "pca"
version = "0.1.0"
description = ""
authors = ["Tomoya Watanabe <tomoya.watanabe@ctc-g.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.112.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
