name: Test Actions

on:
  push:
    branches:
      - "feature/github-actions-test"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }} 
          
      - name: Extract metadata for webex
        id: meta_webex
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}/cic2024-webex
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./webex
          push: true
          tags: ${{ steps.meta_webex.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for langchain
        id: meta_langchain
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}/cic2024-langchain
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./langchain
          push: true
          tags: ${{ steps.meta_langchain.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
              
      - name: Extract metadata for pca
        id: meta_pca
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}/cic2024-pca
                
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./pca
          push: true
          tags: ${{ steps.meta_pca.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
              
      - name: Extract metadata for tester
        id: meta_tester
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}/cic2024-tester
                  
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Tester
          push: true
          tags: ${{ steps.meta_tester.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
      # - name: Build and run Docker Compose
      #   run: docker compose -f compose.yml -f compose-test.yml --profile ci up -d
      # - name: upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: log.html
      #     path: Tester/log.html
