name: Test Actions

on:
  push:
    branches:
      - "feature/github-actions-test"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      # - name: Extract metadata for LangChain
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: twatanabe0808/cic2024-langchain

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./langchain
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}

      - name: Extract metadata for webex
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/cic2024-webex
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./webex
          push: true
          tags: ${{ steps.meta.outputs.tags }}          

      # - name: Build and run Docker Compose
      #   run: docker compose -f compose.yml -f compose-test.yml --profile ci up -d
      # - name: upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: log.html
      #     path: Tester/log.html
