name: Test Actions

on:
  push:
    branches:
      - "feature/github-actions-test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Docker Compose
        run: docker compose -f compose.yml -f compose-test.yml --profile ci up -d
      - name: check files exists
        run: ls -la; ls -la Tester
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: log.html
          path: Tester/log.html